type User @table {
  displayName: String!
  createdAt: Timestamp!
  email: String
  photoUrl: String
}

type Project @table {
  user: User!
  name: String!
  createdAt: Timestamp!
  description: String
  dueDate: Date
  isCompleted: Boolean
}

type Task @table {
  project: Project!
  title: String!
  isCompleted: Boolean!
  createdAt: Timestamp!
  description: String
  dueDate: Date
  priority: String
}